// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// ListPayments is the endpoint for GET /payments.
var ListPayments = openapigo.NewEndpoint[openapigo.NoRequest, []Payment]("GET", "/payments")
