// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// BankTransfer represents the schema.
type BankTransfer struct {
	AccountNumber string `json:"account_number"`
	RoutingNumber string `json:"routing_number"`
}

// CreditCard represents the schema.
type CreditCard struct {
	CardNumber string `json:"card_number"`
	Cvv        string `json:"cvv"`
	ExpMonth   *int64 `json:"exp_month,omitzero"`
	ExpYear    *int64 `json:"exp_year,omitzero"`
}

// FlexValue is a union type (oneOf/anyOf).
type FlexValue = any

// MixedUnion is a union type (oneOf/anyOf).
type MixedUnion = any

// MultiUnion is a union type (oneOf/anyOf).
type MultiUnion = any

// Payment represents the schema.
type Payment struct {
	ID     string      `json:"id"`
	Amount int64       `json:"amount"`
	Method *CreditCard `json:"method,omitzero"`
	Note   *string     `json:"note,omitzero"`
}

// SingleInlineWrapper represents the schema.
type SingleInlineWrapper struct {
	Code  *string `json:"code,omitzero"`
	Label *string `json:"label,omitzero"`
}

// SinglePrimitiveWrapper is a type alias.
type SinglePrimitiveWrapper = string

// SingleRefWrapper is a type alias (single-branch oneOf/anyOf).
type SingleRefWrapper = CreditCard
