// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// ListPets is the endpoint for GET /pets.
var ListPets = openapigo.NewEndpoint[ListPetsParams, []Pet]("GET", "/pets")

// CreatePet is the endpoint for POST /pets.
var CreatePet = openapigo.NewEndpoint[CreatePetParams, Pet]("POST", "/pets").
	WithSuccessCodes(201)

// GetPet is the endpoint for GET /pets/{petId}.
var GetPet = openapigo.NewEndpoint[GetPetParams, Pet]("GET", "/pets/{petId}")

// DeletePet is the endpoint for DELETE /pets/{petId}.
var DeletePet = openapigo.NewEndpoint[DeletePetParams, openapigo.NoContent]("DELETE", "/pets/{petId}").
	WithSuccessCodes(204)
