// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

// ListPetsParams is the request parameters for listPets.
type ListPetsParams struct {
	Limit  *int32     `query:"limit"`
	Status *PetStatus `query:"status"`
}

// CreatePetParams is the request parameters for createPet.
type CreatePetParams struct {
	Body CreatePetRequest `body:"application/json"`
}

// GetPetParams is the request parameters for getPet.
type GetPetParams struct {
	PetID string `path:"petId"`
}

// DeletePetParams is the request parameters for deletePet.
type DeletePetParams struct {
	PetID string `path:"petId"`
}
