// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"fmt"
	"github.com/mkusaka/openapigo"
	"time"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// CreatePetRequest represents the schema.
type CreatePetRequest struct {
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitzero"`
}

// Pet represents the schema.
type Pet struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	Tag       *string    `json:"tag,omitzero"`
	Status    *PetStatus `json:"status,omitzero"`
	CreatedAt *time.Time `json:"createdAt,omitzero"`
}

// PetStatus represents the enum values.
type PetStatus string

const (
	PetStatusActive   PetStatus = "active"
	PetStatusInactive PetStatus = "inactive"
	PetStatusAdopted  PetStatus = "adopted"
)

// PetStatusValues returns all valid values of PetStatus.
func PetStatusValues() []PetStatus {
	return []PetStatus{
		PetStatusActive,
		PetStatusInactive,
		PetStatusAdopted,
	}
}

// Validate checks all constraints on Pet.
func (v Pet) Validate() error {
	var errs openapigo.ValidationErrors
	if v.Status != nil {
		switch string(*v.Status) {
		case "active", "inactive", "adopted":
			// valid
		default:
			errs = append(errs, openapigo.ValidationError{Field: "Status", Constraint: "enum", Message: fmt.Sprintf("invalid value %q", *v.Status)})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}
