// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// Address represents the schema.
type Address struct {
	Street  string  `json:"street"`
	City    string  `json:"city"`
	State   *string `json:"state,omitzero"`
	Zip     *string `json:"zip,omitzero"`
	Country string  `json:"country"`
}

// Payment represents the schema.
type Payment struct {
	Method      string  `json:"method"`
	Amount      float64 `json:"amount"`
	CardNumber  *string `json:"card_number,omitzero"`
	BankAccount *string `json:"bank_account,omitzero"`
}

// Validate checks all constraints on Address.
func (v Address) Validate() error {
	var errs openapigo.ValidationErrors
	if !openapigo.IsZero(v.State) {
		if openapigo.IsZero(v.Zip) {
			errs = append(errs, openapigo.ValidationError{Field: "zip", Constraint: "dependentRequired", Message: "required when state is present"})
		}
	}
	if !openapigo.IsZero(v.Zip) {
		if openapigo.IsZero(v.State) {
			errs = append(errs, openapigo.ValidationError{Field: "state", Constraint: "dependentRequired", Message: "required when zip is present"})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}
