// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// UploadFile is the endpoint for POST /upload.
var UploadFile = openapigo.NewEndpoint[UploadFileParams, UploadFileResponse]("POST", "/upload")

// SendRaw is the endpoint for POST /raw.
var SendRaw = openapigo.NewEndpoint[SendRawParams, openapigo.NoContent]("POST", "/raw").
	WithSuccessCodes(204)

// SendText is the endpoint for POST /text.
var SendText = openapigo.NewEndpoint[SendTextParams, SendTextResponse]("POST", "/text")

// CreatePet is the endpoint for POST /pets.
var CreatePet = openapigo.NewEndpoint[CreatePetParams, Pet]("POST", "/pets").
	WithSuccessCodes(201)

// CreateDocument is the endpoint for POST /documents.
var CreateDocument = openapigo.NewEndpoint[CreateDocumentParams, Document]("POST", "/documents").
	WithSuccessCodes(201)

// BatchUpload is the endpoint for POST /batch-upload.
var BatchUpload = openapigo.NewEndpoint[BatchUploadParams, openapigo.NoContent]("POST", "/batch-upload")

// SendRawNoSchema is the endpoint for POST /raw-no-schema.
var SendRawNoSchema = openapigo.NewEndpoint[SendRawNoSchemaParams, openapigo.NoContent]("POST", "/raw-no-schema").
	WithSuccessCodes(204)
