// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"io"
)

// CreatePetRequestBody supports multiple media types for the request body.
type CreatePetRequestBody struct {
	JSON      *Pet                    `body:"application/json"`
	Multipart *CreatePetMultipartBody `body:"multipart/form-data"`
}

// CreateDocumentRequestBody supports multiple media types for the request body.
type CreateDocumentRequestBody struct {
	JSON *Document `body:"application/json"`
	Form *Document `body:"application/x-www-form-urlencoded"`
	Text *string   `body:"text/plain"`
}

// UploadFileParams is the request parameters for uploadFile.
type UploadFileParams struct {
	Body UploadFileBody `body:"multipart/form-data"`
}

// SendRawParams is the request parameters for sendRaw.
type SendRawParams struct {
	Body io.Reader `body:"application/octet-stream"`
}

// SendTextParams is the request parameters for sendText.
type SendTextParams struct {
	Body *string `body:"text/plain"`
}

// CreatePetParams is the request parameters for createPet.
type CreatePetParams struct {
	Body CreatePetRequestBody `body:"*"`
}

// CreateDocumentParams is the request parameters for createDocument.
type CreateDocumentParams struct {
	Body CreateDocumentRequestBody `body:"*"`
}

// BatchUploadParams is the request parameters for batchUpload.
type BatchUploadParams struct {
	Body BatchUploadBody `body:"multipart/form-data"`
}

// SendRawNoSchemaParams is the request parameters for sendRawNoSchema.
type SendRawNoSchemaParams struct {
	Body io.Reader `body:"application/octet-stream"`
}
