// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// Document represents the schema.
type Document struct {
	Title string  `json:"title"`
	Body  *string `json:"body,omitzero"`
}

// Pet represents the schema.
type Pet struct {
	ID   *int64 `json:"id,omitzero"`
	Name string `json:"name"`
}

// UploadFileBody represents the schema.
type UploadFileBody struct {
	Description *string        `json:"description,omitzero"`
	File        openapigo.File `json:"file"`
}

// UploadFileResponse represents the schema.
type UploadFileResponse struct {
	ID *string `json:"id,omitzero"`
}

// SendTextResponse represents the schema.
type SendTextResponse struct {
	Length *int64 `json:"length,omitzero"`
}

// CreatePetMultipartBody represents the schema.
type CreatePetMultipartBody struct {
	Name  string          `json:"name"`
	Photo *openapigo.File `json:"photo,omitzero"`
}

// BatchUploadBody represents the schema.
type BatchUploadBody struct {
	Files []openapigo.File `json:"files"`
}
