// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// ListItems is the endpoint for GET /items.
var ListItems = openapigo.NewEndpoint[openapigo.NoRequest, []Item]("GET", "/items")
