// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// Base represents the schema.
type Base struct {
	ID   int64   `json:"id"`
	Name *string `json:"name,omitzero"`
}

// ConstrainedInt is a type alias.
type ConstrainedInt = int64

// FlexValue is a union type (oneOf/anyOf).
type FlexValue = any

// Item represents the schema.
type Item struct {
	ID       int64     `json:"id"`
	Name     *string   `json:"name,omitzero"`
	Category string    `json:"category"`
	Tags     *[]string `json:"tags,omitzero"`
}

// MixedUnion is a union type (oneOf/anyOf).
type MixedUnion = any
