// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// CreateUser is the endpoint for POST /users.
var CreateUser = openapigo.NewEndpoint[CreateUserParams, User]("POST", "/users").
	WithSuccessCodes(201)
