// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

// CreateUserParams is the request parameters for createUser.
type CreateUserParams struct {
	Body User `body:"application/json"`
}
