// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
	"time"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// Pet represents the schema.
type Pet struct {
	ID   *int64  `json:"id,omitzero"`
	Name *string `json:"name,omitzero"`
}

// User represents the schema.
type User struct {
	ID        *int64     `json:"id,omitzero"` // read-only
	Name      string     `json:"name"`
	Password  *string    `json:"password,omitzero"`   // write-only
	CreatedAt *time.Time `json:"created_at,omitzero"` // read-only
}

// UserRequest is User without read-only fields (for request bodies).
type UserRequest struct {
	Name     string  `json:"name"`
	Password *string `json:"password,omitzero"`
}

// UserResponse is User without write-only fields (for response bodies).
type UserResponse struct {
	ID        *int64     `json:"id,omitzero"`
	Name      string     `json:"name"`
	CreatedAt *time.Time `json:"created_at,omitzero"`
}

// ToRequest converts User to UserRequest, dropping read-only fields.
func (v User) ToRequest() UserRequest {
	return UserRequest{
		Name:     v.Name,
		Password: v.Password,
	}
}

// ToResponse converts User to UserResponse, dropping write-only fields.
func (v User) ToResponse() UserResponse {
	return UserResponse{
		ID:        v.ID,
		Name:      v.Name,
		CreatedAt: v.CreatedAt,
	}
}
