// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"encoding/json"
	"github.com/mkusaka/openapigo"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// Config represents the schema.
type Config struct {
	Name       string                     `json:"name"`
	Version    *string                    `json:"version,omitzero"`
	Extensions map[string]json.RawMessage `json:"-"`
}

// ConfigWithExtensions represents the schema.
type ConfigWithExtensions struct {
	Extensions  *string                    `json:"extensions,omitzero"`
	Extensions_ map[string]json.RawMessage `json:"-"`
}

// Labels maps string keys to values matching a pattern.
type Labels = map[string]string
