// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"encoding/json"
	"fmt"
	"github.com/mkusaka/openapigo"
	"regexp"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// AllOfWithAdditionalProps represents the schema.
type AllOfWithAdditionalProps struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Extra *string `json:"extra,omitzero"`
}

// AllOfWithPatternProps represents the schema.
type AllOfWithPatternProps struct {
	ID           int64           `json:"id"`
	Name         string          `json:"name"`
	rawFieldKeys map[string]bool `json:"-"`
}

// UnmarshalJSON unmarshals JSON and records raw field keys for unevaluatedProperties checking.
func (v *AllOfWithPatternProps) UnmarshalJSON(data []byte) error {
	type alias AllOfWithPatternProps
	var a alias
	if err := json.Unmarshal(data, &a); err != nil {
		return err
	}
	*v = AllOfWithPatternProps(a)
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	v.rawFieldKeys = make(map[string]bool, len(raw))
	for k := range raw {
		v.rawFieldKeys[k] = true
	}
	return nil
}

// Base represents the schema.
type Base struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Extended represents the schema.
type Extended struct {
	ID           int64           `json:"id"`
	Name         string          `json:"name"`
	Email        string          `json:"email"`
	rawFieldKeys map[string]bool `json:"-"`
}

// UnmarshalJSON unmarshals JSON and records raw field keys for unevaluatedProperties checking.
func (v *Extended) UnmarshalJSON(data []byte) error {
	type alias Extended
	var a alias
	if err := json.Unmarshal(data, &a); err != nil {
		return err
	}
	*v = Extended(a)
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	v.rawFieldKeys = make(map[string]bool, len(raw))
	for k := range raw {
		v.rawFieldKeys[k] = true
	}
	return nil
}

// OneOfUneval represents the schema.
type OneOfUneval struct {
	Kind         string          `json:"kind"`
	Whiskers     *float64        `json:"whiskers,omitzero"`
	Bark         *bool           `json:"bark,omitzero"`
	rawFieldKeys map[string]bool `json:"-"`
}

// UnmarshalJSON unmarshals JSON and records raw field keys for unevaluatedProperties checking.
func (v *OneOfUneval) UnmarshalJSON(data []byte) error {
	type alias OneOfUneval
	var a alias
	if err := json.Unmarshal(data, &a); err != nil {
		return err
	}
	*v = OneOfUneval(a)
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	v.rawFieldKeys = make(map[string]bool, len(raw))
	for k := range raw {
		v.rawFieldKeys[k] = true
	}
	return nil
}

// Point is a tuple type with 2 prefix items.
type Point []any

// Validate checks that no unevaluated items are present.
func (v Point) Validate() error {
	if len(v) > 2 {
		return openapigo.ValidationErrors{openapigo.ValidationError{Field: "items", Constraint: "unevaluatedItems", Message: fmt.Sprintf("array has %d items, maximum allowed is 2", len(v))}}
	}
	return nil
}

// PointWithBoolLabel is a tuple type with 1 prefix items.
type PointWithBoolLabel []any

// Validate checks that unevaluated items match the required type.
func (v PointWithBoolLabel) Validate() error {
	var errs openapigo.ValidationErrors
	for i := 1; i < len(v); i++ {
		if _, ok := v[i].(bool); !ok {
			errs = append(errs, openapigo.ValidationError{Field: fmt.Sprintf("[%d]", i), Constraint: "unevaluatedItems", Message: fmt.Sprintf("item %d: expected boolean", i)})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

// PointWithIntLabel is a tuple type with 1 prefix items.
type PointWithIntLabel []any

// Validate checks that unevaluated items match the required type.
func (v PointWithIntLabel) Validate() error {
	var errs openapigo.ValidationErrors
	for i := 1; i < len(v); i++ {
		if f, ok := v[i].(float64); !ok || f != float64(int64(f)) {
			errs = append(errs, openapigo.ValidationError{Field: fmt.Sprintf("[%d]", i), Constraint: "unevaluatedItems", Message: fmt.Sprintf("item %d: expected integer", i)})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

// PointWithItems is a tuple type with 2 prefix items.
type PointWithItems []any

// PointWithLabel is a tuple type with 2 prefix items.
type PointWithLabel []any

// Validate checks that unevaluated items match the required type.
func (v PointWithLabel) Validate() error {
	var errs openapigo.ValidationErrors
	for i := 2; i < len(v); i++ {
		if _, ok := v[i].(string); !ok {
			errs = append(errs, openapigo.ValidationError{Field: fmt.Sprintf("[%d]", i), Constraint: "unevaluatedItems", Message: fmt.Sprintf("item %d: expected string", i)})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

// PointWithNumLabel is a tuple type with 1 prefix items.
type PointWithNumLabel []any

// Validate checks that unevaluated items match the required type.
func (v PointWithNumLabel) Validate() error {
	var errs openapigo.ValidationErrors
	for i := 1; i < len(v); i++ {
		if _, ok := v[i].(float64); !ok {
			errs = append(errs, openapigo.ValidationError{Field: fmt.Sprintf("[%d]", i), Constraint: "unevaluatedItems", Message: fmt.Sprintf("item %d: expected number", i)})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

var patternUnevalAllOfWithPatternProps0 = regexp.MustCompile("^x-")

// Validate checks all constraints on AllOfWithPatternProps.
func (v AllOfWithPatternProps) Validate() error {
	var errs openapigo.ValidationErrors
	evaluated := map[string]bool{
		"id":   true,
		"name": true,
	}
	for k := range v.rawFieldKeys {
		if evaluated[k] {
			continue
		}
		if patternUnevalAllOfWithPatternProps0.MatchString(k) {
			continue
		}
		errs = append(errs, openapigo.ValidationError{Field: k, Constraint: "unevaluatedProperties", Message: fmt.Sprintf("unevaluated property %q", k)})
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

// Validate checks all constraints on Extended.
func (v Extended) Validate() error {
	var errs openapigo.ValidationErrors
	evaluated := map[string]bool{
		"email": true,
		"id":    true,
		"name":  true,
	}
	for k := range v.rawFieldKeys {
		if !evaluated[k] {
			errs = append(errs, openapigo.ValidationError{Field: k, Constraint: "unevaluatedProperties", Message: fmt.Sprintf("unevaluated property %q", k)})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

// Validate checks all constraints on OneOfUneval.
func (v OneOfUneval) Validate() error {
	var errs openapigo.ValidationErrors
	evaluated := map[string]bool{
		"kind": true,
	}
	// oneOf branch 0
	if v.rawFieldKeys["whiskers"] {
		evaluated["whiskers"] = true
	}
	// oneOf branch 1
	if v.rawFieldKeys["bark"] {
		evaluated["bark"] = true
	}
	for k := range v.rawFieldKeys {
		if !evaluated[k] {
			errs = append(errs, openapigo.ValidationError{Field: k, Constraint: "unevaluatedProperties", Message: fmt.Sprintf("unevaluated property %q", k)})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}
