// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// ListPets is the endpoint for GET /pets.
var ListPets = openapigo.NewEndpoint[openapigo.NoRequest, []Pet]("GET", "/pets")

// CreatePet is the endpoint for POST /pets.
var CreatePet = openapigo.NewEndpoint[CreatePetParams, Pet]("POST", "/pets").
	WithSuccessCodes(201)

// ListOwners is the endpoint for GET /owners.
var ListOwners = openapigo.NewEndpoint[openapigo.NoRequest, []Owner]("GET", "/owners")
