// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

// CreatePetParams is the request parameters for createPet.
type CreatePetParams struct {
	Body Pet `body:"application/json"`
}
