// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"github.com/mkusaka/openapigo"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// Owner represents the schema.
type Owner struct {
	ID    *int64  `json:"id,omitzero"`
	Name  string  `json:"name"`
	Email *string `json:"email,omitzero"`
}

// Pet represents the schema.
type Pet struct {
	ID   *int64 `json:"id,omitzero"`
	Name string `json:"name"`
}
