package generate

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// writeFile writes Go source code to a file, formatting with gofmt.
func writeFile(path string, content []byte) error {
	formatted, err := format.Source(content)
	if err != nil {
		// Write unformatted for debugging.
		os.WriteFile(path+".unformatted", content, 0o644)
		return fmt.Errorf("gofmt %s: %w", filepath.Base(path), err)
	}
	return os.WriteFile(path, formatted, 0o644)
}

// fileHeader returns the standard header for generated files.
func fileHeader(pkg, source string) string {
	return fmt.Sprintf(`// Code generated by openapigo. DO NOT EDIT.
//
// Source: %s
// Generator version: 0.1.0
package %s
`, source, pkg)
}
