package generate

import (
	"bufio"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// generatedFileHeader is the marker comment used to identify generated files.
const generatedFileHeader = "// Code generated by openapigo. DO NOT EDIT."

// writeFileAtomic writes Go source code to a file using tmp-then-rename
// for atomic writes. The content is formatted with gofmt before writing.
func writeFileAtomic(path string, content []byte) error {
	formatted, err := format.Source(content)
	if err != nil {
		// Write unformatted for debugging.
		_ = os.WriteFile(path+".unformatted", content, 0o644)
		return fmt.Errorf("gofmt %s: %w", filepath.Base(path), err)
	}

	// Write to a temp file in the same directory (same filesystem for atomic rename).
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".openapigo-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(formatted); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("write temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("close temp file: %w", err)
	}

	// Atomic rename.
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("rename %s → %s: %w", filepath.Base(tmpPath), filepath.Base(path), err)
	}
	return nil
}

// cleanStaleFiles removes previously generated files that are no longer
// in the current output set. A file is considered generated if its first
// line matches the generatedFileHeader constant.
func cleanStaleFiles(dir string, currentFiles map[string]bool) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil // directory may not exist yet on first run
	}
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".go" {
			continue
		}
		if currentFiles[e.Name()] {
			continue // file is in current output set
		}
		path := filepath.Join(dir, e.Name())
		if isGeneratedFile(path) {
			if err := os.Remove(path); err != nil {
				return fmt.Errorf("remove stale file %s: %w", e.Name(), err)
			}
		}
	}
	return nil
}

// isGeneratedFile reports whether a file starts with the generated header.
func isGeneratedFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	if scanner.Scan() {
		return strings.HasPrefix(scanner.Text(), generatedFileHeader)
	}
	return false
}

// fileHeader returns the standard header for generated files.
// Both source and pkg are sanitized to prevent code injection.
func fileHeader(pkg, source string) string {
	return fmt.Sprintf(`%s
//
// Source: %s
// Generator version: 0.1.0
package %s
`, generatedFileHeader, sanitizeComment(source), sanitizeIdentifier(pkg))
}

// SanitizePackageName converts an arbitrary directory name into a valid Go package name.
func SanitizePackageName(name string) string {
	// Replace hyphens and dots with underscores.
	name = strings.NewReplacer("-", "_", ".", "_").Replace(name)
	// Lowercase.
	name = strings.ToLower(name)
	// Remove any characters that are not letters, digits, or underscores.
	var b strings.Builder
	for _, r := range name {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' || r == '_' {
			b.WriteRune(r)
		}
	}
	name = b.String()
	if name == "" {
		return "api"
	}
	// Leading digits: prefix with "pkg".
	if name[0] >= '0' && name[0] <= '9' {
		name = "pkg" + name
	}
	// "main" cannot be imported.
	if name == "main" {
		name = "main_api"
	}
	// Go reserved words.
	if reserved[name] {
		name = name + "_api"
	}
	return name
}
