// Code generated by openapigo. DO NOT EDIT.
//
// Source: spec.json
// Generator version: 0.1.0
package generated

import (
	"fmt"
	"github.com/mkusaka/openapigo"
	"regexp"
)

// Ensures generated code is compatible with the runtime library.
var _ = openapigo.RuntimeCompatV0_1

// NoConstraints represents the schema.
type NoConstraints struct {
	Name *string `json:"name,omitzero"`
}

// Product represents the schema.
type Product struct {
	Name        string    `json:"name"`
	Description *string   `json:"description,omitzero"`
	Price       float64   `json:"price"`
	Quantity    int64     `json:"quantity"`
	Tags        *[]string `json:"tags,omitzero"`
	Status      *string   `json:"status,omitzero"`
	Sku         *string   `json:"sku,omitzero"`
}

var patternProductSku = regexp.MustCompile("^[A-Z]{2}-[0-9]{4}$")

// Validate checks all constraints on Product.
func (v Product) Validate() error {
	var errs openapigo.ValidationErrors
	if len(v.Name) < 1 {
		errs = append(errs, openapigo.ValidationError{Field: "Name", Constraint: "minLength", Message: fmt.Sprintf("length %d is less than minimum 1", len(v.Name))})
	}
	if len(v.Name) > 100 {
		errs = append(errs, openapigo.ValidationError{Field: "Name", Constraint: "maxLength", Message: fmt.Sprintf("length %d exceeds maximum 100", len(v.Name))})
	}
	if v.Description != nil {
		if len(*v.Description) > 1000 {
			errs = append(errs, openapigo.ValidationError{Field: "Description", Constraint: "maxLength", Message: fmt.Sprintf("length %d exceeds maximum 1000", len(*v.Description))})
		}
	}
	if v.Price < 0 {
		errs = append(errs, openapigo.ValidationError{Field: "Price", Constraint: "minimum", Message: fmt.Sprintf("value %v is less than minimum 0", v.Price)})
	}
	if v.Price <= 0 {
		errs = append(errs, openapigo.ValidationError{Field: "Price", Constraint: "exclusiveMinimum", Message: fmt.Sprintf("value %v must be greater than 0", v.Price)})
	}
	if v.Quantity < 0 {
		errs = append(errs, openapigo.ValidationError{Field: "Quantity", Constraint: "minimum", Message: fmt.Sprintf("value %v is less than minimum 0", v.Quantity)})
	}
	if v.Quantity > 10000 {
		errs = append(errs, openapigo.ValidationError{Field: "Quantity", Constraint: "maximum", Message: fmt.Sprintf("value %v exceeds maximum 10000", v.Quantity)})
	}
	if v.Tags != nil {
		if len(*v.Tags) < 1 {
			errs = append(errs, openapigo.ValidationError{Field: "Tags", Constraint: "minItems", Message: fmt.Sprintf("length %d is less than minimum 1", len(*v.Tags))})
		}
		if len(*v.Tags) > 10 {
			errs = append(errs, openapigo.ValidationError{Field: "Tags", Constraint: "maxItems", Message: fmt.Sprintf("length %d exceeds maximum 10", len(*v.Tags))})
		}
	}
	if v.Status != nil {
		switch string(*v.Status) {
		case "draft", "active", "archived":
			// valid
		default:
			errs = append(errs, openapigo.ValidationError{Field: "Status", Constraint: "enum", Message: fmt.Sprintf("invalid value %q", *v.Status)})
		}
	}
	if v.Sku != nil {
		if !patternProductSku.MatchString(string(*v.Sku)) {
			errs = append(errs, openapigo.ValidationError{Field: "Sku", Constraint: "pattern", Message: "does not match pattern"})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}
